package to.eyed.spettro.chat.data.tools

import org.mozilla.javascript.Context
import org.mozilla.javascript.ContextFactory
import org.mozilla.javascript.NativeJSON
import org.mozilla.javascript.Scriptable
import org.mozilla.javascript.ScriptableObject
import org.mozilla.javascript.Undefined
import to.eyed.spettro.chat.data.artifacts.ArtifactRef

/**
 * The run-javascript tool: an embedded Rhino interpreter locked down to pure
 * computation. The sandbox has no Java bridge (a ClassShutter denies every
 * class, and the scope is initialized without LiveConnect globals), no
 * network, no filesystem except [ArtifactStore] via the `saveFile` helper,
 * and a hard wall-clock deadline enforced from the instruction observer.
 * Interpreted mode only — Android cannot load Rhino-generated bytecode, and
 * the instruction observer needs it anyway.
 */
internal class JsTools(private val saveArtifact: (name: String, content: String) -> ArtifactRef) {
    private companion object {
        const val TIMEOUT_MS = 10_000L
        const val MAX_CODE_CHARS = 100_000
        const val MAX_CONSOLE_CHARS = 16_000
        const val MAX_RESULT_CHARS = 10_000
        const val MAX_SAVED_FILES = 8
    }

    private class TimeoutError : Error("script timed out")

    private class SandboxFactory : ContextFactory() {
        override fun makeContext(): Context {
            val cx = super.makeContext()
            cx.isInterpretedMode = true
            cx.instructionObserverThreshold = 50_000
            cx.maximumInterpreterStackDepth = 1_000
            cx.setClassShutter { false } // no Java class is visible, ever
            cx.languageVersion = Context.VERSION_ES6
            return cx
        }

        override fun observeInstructionCount(cx: Context, instructionCount: Int) {
            val deadline = cx.getThreadLocal("deadline") as? Long ?: return
            if (System.currentTimeMillis() > deadline) throw TimeoutError()
        }
    }

    private val factory = SandboxFactory()

    fun run(argumentsJson: String): ToolResult {
        val code = ToolArgs.string(argumentsJson, "code")
            ?: return ToolResult("run-javascript requires code", isError = true)
        if (code.length > MAX_CODE_CHARS) {
            return ToolResult("run-javascript: the script is too long (max $MAX_CODE_CHARS chars)", isError = true)
        }

        val console = StringBuilder()
        val saved = mutableListOf<ArtifactRef>()
        val cx = factory.enterContext()
        try {
            cx.putThreadLocal("deadline", System.currentTimeMillis() + TIMEOUT_MS)
            // Safe standard objects: Object/Array/JSON/Math/…, and none of
            // the LiveConnect globals (Packages, java, getClass).
            val scope: ScriptableObject = cx.initSafeStandardObjects(null, false)
            installConsole(scope, console)
            installSaveFile(scope, saved)

            val result = cx.evaluateString(scope, code, "script.js", 1, null)

            val sb = StringBuilder()
            val rendered = render(cx, scope, result)
            if (rendered != null) sb.append("Result: ").append(rendered.take(MAX_RESULT_CHARS)).append('\n')
            if (console.isNotEmpty()) {
                sb.append("Console output:\n").append(console.toString().take(MAX_CONSOLE_CHARS))
                if (!sb.endsWith("\n")) sb.append('\n')
            }
            if (saved.isNotEmpty()) {
                sb.append("Saved files (the user sees them as attachments on this message):\n")
                saved.forEach { sb.append(it.line).append('\n') }
            }
            if (sb.isEmpty()) sb.append("The script ran but produced no result, console output, or files.")
            return ToolResult(sb.toString().trimEnd())
        } catch (e: TimeoutError) {
            return ToolResult(
                "run-javascript: the script exceeded the ${TIMEOUT_MS / 1000}s limit and was stopped. " +
                    "Simplify it or process less data per call.",
                isError = true,
            )
        } catch (e: Exception) {
            // Rhino surfaces JS errors (RhinoException) with file:line detail.
            return ToolResult("run-javascript: ${e.message?.take(600) ?: "script error"}", isError = true)
        } finally {
            Context.exit()
        }
    }

    /** console.log/info/warn/error and a print alias, captured into [buffer]. */
    private fun installConsole(scope: ScriptableObject, buffer: StringBuilder) {
        val console = org.mozilla.javascript.NativeObject()
        for (level in listOf("log", "info", "warn", "error", "debug")) {
            val fn = org.mozilla.javascript.LambdaFunction(scope, level, 1) { cx, s, _, args ->
                if (buffer.length < MAX_CONSOLE_CHARS) {
                    buffer.append(args.joinToString(" ") { arg -> render(cx, s, arg) ?: "undefined" })
                    buffer.append('\n')
                }
                Undefined.instance
            }
            console.put(level, console, fn)
        }
        scope.put("console", scope, console)
        scope.put(
            "print", scope,
            org.mozilla.javascript.LambdaFunction(scope, "print", 1) { cx, s, _, args ->
                if (buffer.length < MAX_CONSOLE_CHARS) {
                    buffer.append(args.joinToString(" ") { arg -> render(cx, s, arg) ?: "undefined" })
                    buffer.append('\n')
                }
                Undefined.instance
            },
        )
    }

    /** saveFile(name, content): writes a text artifact; returns the stored name. */
    private fun installSaveFile(scope: ScriptableObject, saved: MutableList<ArtifactRef>) {
        scope.put(
            "saveFile", scope,
            org.mozilla.javascript.LambdaFunction(scope, "saveFile", 2) { cx, s, _, args ->
                if (saved.size >= MAX_SAVED_FILES) {
                    throw org.mozilla.javascript.JavaScriptException(
                        "saveFile: at most $MAX_SAVED_FILES files per run", "script.js", 0,
                    )
                }
                val name = args.getOrNull(0)?.let { Context.toString(it) } ?: "file.txt"
                val content = args.getOrNull(1)?.let { arg ->
                    if (arg is String) arg else render(cx, s, arg)
                } ?: ""
                val ref = saveArtifact(name, content)
                saved += ref
                ref.fileName
            },
        )
    }

    /** A model-readable rendering of a JS value; null when undefined. */
    private fun render(cx: Context, scope: Scriptable, value: Any?): String? = when {
        value == null -> "null"
        Undefined.isUndefined(value) -> null
        value is String -> value
        value is Number || value is Boolean -> Context.toString(value)
        else -> runCatching {
            NativeJSON.stringify(cx, scope, value, null, 2).let {
                if (Undefined.isUndefined(it)) Context.toString(value) else Context.toString(it)
            }
        }.getOrElse { runCatching { Context.toString(value) }.getOrDefault(value.toString()) }
    }
}
